name: Generate Stats Images
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jstrieb/github-stats@master
        with:
          username: devOlvr
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GENERATE_LANGUAGE_PIE_CHART: false
